name: My First workflow

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Welcome message
          run: echo "my first Github Actions Job"
        
        - name: List and Read files
          run: |
            ls -ltra
            cat README.md
          
        